plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - RacerAssembly.md
  - ThumbtrollerAssembly.md
  - Manual.md
  - QuickStart.md
  - images/
markdown: GFM
